# permissions for end users to edit servertopologies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: loc-server
    app.kubernetes.io/managed-by: kustomize
  name: servertopology-editor-role
rules:
- apiGroups:
  - loc.palpark.me
  resources:
  - servertopologies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - loc.palpark.me
  resources:
  - servertopologies/status
  verbs:
  - get
